### ISSUE TITLE
Broken Link in README

### ISSUE THREAD

**Issue by tajmone** [practical-markup-language/user-manual#1]
In the main README the link to the PML User Manual is broken:

https://www.pml-lang.dev/docs/PML_User_Manual.html

I can't create a PR for this since the repository hasn't been updated to PML 1.3.0 yet.

**Comment by pml-lang** [comment]
I will fix the link when I move this repository to `@pml-lang`.

**Comment by practical-programming** [comment]
This repository has been replaced by https://github.com/pml-lang/user-manual.
The error has been fixed in the new repository

**Comment by tajmone** [comment]
> This repository has been replaced by https://github.com/pml-lang/user-manual.

I think this was a good move, having two separate GitHub organizations for PML could be confusing (in regard to which type of assets could go where) and would make the project look "thinner".
