### ISSUE TITLE
PML Docs: Required Parameters' ID Formal Definition

### ISSUE THREAD

**Issue by tajmone** [practical-markup-language/user-manual#2]
It would be really useful if the documentation would specify what constitutes a valid parameter identifier, by using a Regular Expression notation, and maybe also a railroad diagram (aka Syntax diagram), which might be easier to understand for non-programmers:

- [ ]  [PML User Manual » Parameters] 
- [ ]  [PML Reference Manual » Constant Parameter] 

While working on my PML syntax for Sublime Text, I couldn't find references to these type of issues (peeking at PPL sources seems the only option right now, but that's time consuming).

-------------------------------------------------------------------------------

### References

- [Wikipedia » Syntax diagram](https://en.wikipedia.org/wiki/Syntax_diagram)
- https://www.json.org/json-en.html — the JSON spec shown as a RR diagram.

Railroad diagrams (RRD) generators:

- https://www.bottlecaps.de/rr/ui — converts EBNF grammars to RRD.
    + https://github.com/GuntherRademacher/rr — Java sources.
- https://regexper.com/#%5Ba-zA-Z_%5D%5Ba-zA-Z_0-9%5D* — converts RegEx to RRD.

Misc RRD generator libraries:

- https://tabatkins.github.io/railroad-diagrams/
- https://github.com/Chrriis/RRDiagram — Java
- https://pypi.org/project/railroad-diagrams/ — Python

Miscellanea:

- https://atom.io/packages/regex-railroad-diagram — editor package to show RegExs as RRD.

[railroad diagram]: https://en.wikipedia.org/wiki/Syntax_diagram "Wikipedia » Syntax diagram"
[PML User Manual » Parameters]: https://www.pml-lang.dev/docs/user_manual/index.html#ch__11
[PML Reference Manual » Constant Parameter]: https://www.pml-lang.dev/docs/reference_manual/index.html#node_constant

**Comment by pml-lang** [comment]
> what constitutes a valid parameter identifier

You're right - that should be explained in the manual. Will fix that.

> railroad diagram

I love railroad diagrams. 
Thanks for sharing these useful links.
The EBNF of PML's grammar should be on PML's website. And railroad diagrams would be the cherry on the cake.

**Comment by pml-lang** [comment]
The format of a valid parameter identifier is now specified in the [manual](https://www.pml-lang.dev/docs/user_manual/index.html#ch__11).
Regex: `[a-zA-Z][a-zA-Z0-9_]*`
The change has been pushed to [Github](https://github.com/pml-lang/user-manual/blob/main/input/text/07_05_parameters.pml)

**Comment by practical-programming** [comment]
Adding railroad diagrams is an excellent idea. I've added it to my to-do list.
